# It's useful for debugging and error output to keep the *values* of these vtypes as strings.

# Arithmetic
ADD = "ADD"
SUBTRACT = "SUBTRACT"
MULTIPLY = "MULTIPLY"
DIVIDE = "DIVIDE"
UMINUS = "UMINUS"
MODULUS = "MODULUS"
POWER = "POWER"

# Basic types
INTEGER_VALUE = "INTEGER_VALUE"
FLOAT_VALUE = "FLOAT_VALUE"
BOOLEAN_VALUE = "BOOLEAN_VALUE"
NONE_VALUE = "NONE_VALUE"
STRING_VALUE = "STRING_VALUE"

# Basic type keywords
INT_KEYWORD = "INT_KEYWORD"
FLOAT_KEYWORD = "FLOAT_KEYWORD"
STRING_KEYWORD = "STRING_KEYWORD"
BOOLEAN_KEYWORD = "BOOLEAN_KEYWORD"

# Boolean operators
OR = "OR"
AND = "AND"
NOT = "NOT"

# String operators
CONCATENATE = "CONCATENATE"

# Equality
EQUAL = "EQUAL"
NOT_EQUAL = "NOT_EQUAL"

# Relational
LESS_THAN = "LESS_THAN"
GREATER_THAN = "GREATER_THAN"
LESS_THAN_EQUAL = "LESS_THAN_EQUAL"
GREATER_THAN_EQUAL = "GREATER_THAN_EQUAL"

#Control Flow
WHILE = "WHILE"
IF = "IF"
ELIF = "ELIF"
IF_ELSE = "IF_ELSE"

#List Declarations
LIST_TYPE = "LIST_TYPE"
BRACKET_DECL = "BRACKET_DECL"

# Other
ASSIGNMENT = "ASSIGNMENT"
IDENTIFIER = "IDENTIFIER"
DECLARATION = "DECLARATION"
DECLARATION_ASSIGNMENT = "DECLARATION_ASSIGNMENT"
STAT_LIST = "STAT_LIST"
STAT_NEWLINE = "STAT_NEWLINE"
#EPSILON_STAT = "EPSILON_STAT" #blank statement
